-- Create contratos table
CREATE TABLE IF NOT EXISTS public.contratos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE CASCADE,
    area_id BIGINT REFERENCES public.areas(id) ON DELETE SET NULL,
    servico_id BIGINT REFERENCES public.servicos(id) ON DELETE SET NULL,
    produto_id BIGINT REFERENCES public.produtos(id) ON DELETE SET NULL,
    tipo_contrato TEXT CHECK (tipo_contrato IN ('fixo mensal', 'projeto', 'horas', 'pro labore', 'mensalidade de processo')),
    valor_contrato NUMERIC(15, 2),
    data_inicio DATE,
    data_fim DATE,
    quem_trouxe TEXT,
    empresa_id BIGINT REFERENCES public.empresas(id) ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE public.contratos ENABLE ROW LEVEL SECURITY;

-- Create policies for contratos
CREATE POLICY "Authenticated users can view contratos from their company" 
ON public.contratos 
FOR SELECT 
TO authenticated 
USING (
    empresa_id IN (
        SELECT id FROM public.empresas WHERE user_id = auth.uid()
    )
);

CREATE POLICY "Authenticated users can insert contratos to their company" 
ON public.contratos 
FOR INSERT 
TO authenticated 
WITH CHECK (
    empresa_id IN (
        SELECT id FROM public.empresas WHERE user_id = auth.uid()
    )
);

CREATE POLICY "Authenticated users can update contratos from their company" 
ON public.contratos 
FOR UPDATE 
TO authenticated 
USING (
    empresa_id IN (
        SELECT id FROM public.empresas WHERE user_id = auth.uid()
    )
);

CREATE POLICY "Authenticated users can delete contratos from their company" 
ON public.contratos 
FOR DELETE 
TO authenticated 
USING (
    empresa_id IN (
        SELECT id FROM public.empresas WHERE user_id = auth.uid()
    )
);

-- Create indexes for better performance
CREATE INDEX idx_contratos_cliente_id ON public.contratos(cliente_id);
CREATE INDEX idx_contratos_empresa_id ON public.contratos(empresa_id);
CREATE INDEX idx_contratos_area_id ON public.contratos(area_id);
CREATE INDEX idx_contratos_servico_id ON public.contratos(servico_id);
CREATE INDEX idx_contratos_produto_id ON public.contratos(produto_id);

